name: Publish Github Pages

on:
  push:
    branches: [main]

# Cancel any in-progress job or run
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
concurrency:
  group: gh-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_deploy_docs:
    runs-on: ubuntu-latest
    name: Build Doxygen documentation and deploy
    environment:
      name: github-pages
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v2
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: dia doxygen doxygen-doc doxygen-gui doxygen-latex graphviz mscgen
          version: 1.0

      - name: Build
        run: |
          sudo locale-gen en_US.UTF-8
          sudo update-locale

      - name: Deploy
        uses: sphinx-notes/pages@v3
        with:
          documentation_path: ./docs/source
          requirements_path: ./requirements.txt
          cache: true
